
package com.zgc.base.WebServiceClient.User;

import com.zgc.base.WebServiceClient.User.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserWebService", targetNamespace = "http://WebService.base.zgc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserInfo", targetNamespace = "http://WebService.base.zgc.com/", className = "com.zgc.base.WebServiceClient.User.GetUserInfo")
    @ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "http://WebService.base.zgc.com/", className = "com.zgc.base.WebServiceClient.User.GetUserInfoResponse")
    public String getUserInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
